name: Validate Pull Request

on:
   workflow_call:
    inputs:
      github-event-action:
        required: true
        type: string
      github-event-pull_request-body:
        required: true
        type: string
      github-event-pull_request-_links-html-href:
        required: true
        type: string
      github-actor:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_CHANNEL_ALERTS_PULL_REQUESTS:
        required: true
      MONDAY_API_KEY:
        required: true

jobs:

  validate_pr:
    name: Check Pull Request
    if: ${{ inputs.github-event-action  == 'created' || inputs.github-event-action == 'opened' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the shared-workflows repo to access the scripts
        uses: actions/checkout@V2
        with:
          repository: timehop/shared-workflows
          path: shared-workflows

      - name: Check if PR has a monday.com valid url
        run: |
          ruby shared-workflows/scripts/validate_pr_description.rb "${{ inputs.github-event-pull_request-body }}"

      - name: Notify PR was created on Slack
        run: |
          ruby shared-workflows/scripts/notify_on_slack.rb "${{ inputs.github-event-pull_request-_links-html-href }} created by ${{ inputs.github-actor }}" ${{ secrets.SLACK_WEBHOOK_CHANNEL_ALERTS_PULL_REQUESTS }}

      - name: Post update on monday pulse
        run: |
          ruby shared-workflows/scripts/create_monday_update.rb "${{ inputs.github-event-pull_request-body }}" ${{ secrets.MONDAY_API_KEY }} "Pull request ${{ inputs.github-event-pull_request-_links-html-href }} created by ${{ inputs.github-actor }}"
